/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author Abdessamed
 */
public class SignatureVue extends javax.swing.JFrame {

    /**
     * Creates new form SignatureVue
     */
    public SignatureVue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel19 = new javax.swing.JPanel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel131 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel117 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel103 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel89 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel75 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel19.setBackground(new java.awt.Color(23, 36, 50));
        jPanel19.setPreferredSize(new java.awt.Dimension(450, 400));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel127.setFont(new java.awt.Font("Cairo SemiBold", 1, 18)); // NOI18N
        jLabel127.setForeground(new java.awt.Color(255, 255, 255));
        jLabel127.setText("إسم العامل");
        jPanel19.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jLabel128.setFont(new java.awt.Font("Cairo SemiBold", 0, 16)); // NOI18N
        jLabel128.setForeground(new java.awt.Color(255, 255, 255));
        jLabel128.setText("الرتبة المهنية");
        jPanel19.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        jLabel129.setFont(new java.awt.Font("Cairo SemiBold", 0, 16)); // NOI18N
        jLabel129.setForeground(new java.awt.Color(255, 255, 255));
        jLabel129.setText("تاريخ التنصيب");
        jPanel19.add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        jTextField18.setText("jTextField3");
        jPanel19.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 200, 45));

        jTextField19.setText("jTextField4");
        jPanel19.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 200, 45));

        jButton11.setFont(new java.awt.Font("Cairo ExtraBold", 1, 18)); // NOI18N
        jButton11.setText("إلغاء");
        jPanel19.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 100, 40));

        jButton12.setFont(new java.awt.Font("Cairo ExtraBold", 1, 18)); // NOI18N
        jButton12.setText("مصادقة");
        jPanel19.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 310, 100, 40));

        jLabel131.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icons8-immigration-64.png"))); // NOI18N
        jPanel19.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 70, -1));

        jPanel10.setBackground(new java.awt.Color(23, 36, 50));
        jPanel10.setPreferredSize(new java.awt.Dimension(450, 400));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel113.setFont(new java.awt.Font("Cairo SemiBold", 1, 18)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(255, 255, 255));
        jLabel113.setText("إسم التلميذ");
        jPanel10.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 25, -1, -1));

        jLabel114.setFont(new java.awt.Font("Cairo SemiBold", 0, 16)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(255, 255, 255));
        jLabel114.setText("السنة الدراسية");
        jPanel10.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 100, -1, -1));

        jLabel115.setFont(new java.awt.Font("Cairo SemiBold", 0, 16)); // NOI18N
        jLabel115.setForeground(new java.awt.Color(255, 255, 255));
        jLabel115.setText("القسم");
        jPanel10.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 170, -1, -1));

        jLabel116.setFont(new java.awt.Font("Cairo SemiBold", 0, 16)); // NOI18N
        jLabel116.setForeground(new java.awt.Color(255, 255, 255));
        jLabel116.setText("المعدل");
        jPanel10.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        jTextField14.setText("jTextField3");
        jPanel10.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 200, 45));

        jTextField15.setText("jTextField4");
        jPanel10.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 200, 45));

        jTextField16.setText("jTextField5");
        jPanel10.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 200, 45));

        jButton9.setFont(new java.awt.Font("Cairo ExtraBold", 1, 18)); // NOI18N
        jButton9.setText("إلغاء");
        jPanel10.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 100, 40));

        jButton10.setFont(new java.awt.Font("Cairo ExtraBold", 1, 18)); // NOI18N
        jButton10.setText("مصادقة");
        jPanel10.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 310, 100, 40));

        jLabel117.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icons8-immigration-64.png"))); // NOI18N
        jPanel10.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 70, -1));

        jPanel8.setBackground(new java.awt.Color(23, 36, 50));
        jPanel8.setPreferredSize(new java.awt.Dimension(450, 400));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel99.setFont(new java.awt.Font("Cairo SemiBold", 1, 18)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(255, 255, 255));
        jLabel99.setText("إسم التلميذ");
        jPanel8.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 25, -1, -1));

        jLabel100.setFont(new java.awt.Font("Cairo SemiBold", 0, 16)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(255, 255, 255));
        jLabel100.setText("السنة الدراسية");
        jPanel8.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        jLabel101.setFont(new java.awt.Font("Cairo SemiBold", 0, 16)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(255, 255, 255));
        jLabel101.setText("القسم");
        jPanel8.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jTextField10.setText("jTextField3");
        jPanel8.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 200, 45));

        jTextField11.setText("jTextField4");
        jPanel8.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 200, 45));

        jButton7.setFont(new java.awt.Font("Cairo ExtraBold", 1, 18)); // NOI18N
        jButton7.setText("إلغاء");
        jPanel8.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 100, 40));

        jButton8.setFont(new java.awt.Font("Cairo ExtraBold", 1, 18)); // NOI18N
        jButton8.setText("مصادقة");
        jPanel8.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 100, 40));

        jLabel103.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icons8-immigration-64.png"))); // NOI18N
        jPanel8.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 70, -1));

        jPanel6.setBackground(new java.awt.Color(23, 36, 50));
        jPanel6.setPreferredSize(new java.awt.Dimension(450, 400));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel85.setFont(new java.awt.Font("Cairo SemiBold", 1, 18)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(255, 255, 255));
        jLabel85.setText("إسم التلميذ");
        jPanel6.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 25, -1, -1));

        jLabel86.setFont(new java.awt.Font("Cairo SemiBold", 0, 16)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 255, 255));
        jLabel86.setText("السنة الدراسية");
        jPanel6.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 100, -1, -1));

        jLabel87.setFont(new java.awt.Font("Cairo SemiBold", 0, 16)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(255, 255, 255));
        jLabel87.setText("القسم");
        jPanel6.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 170, -1, -1));

        jLabel88.setFont(new java.awt.Font("Cairo SemiBold", 0, 16)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(255, 255, 255));
        jLabel88.setText("سبب الاستدعاء");
        jPanel6.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        jTextField6.setText("jTextField3");
        jPanel6.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 200, 45));

        jTextField7.setText("jTextField4");
        jPanel6.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 200, 45));

        jTextField8.setText("jTextField5");
        jPanel6.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 200, 45));

        jButton5.setFont(new java.awt.Font("Cairo ExtraBold", 1, 18)); // NOI18N
        jButton5.setText("إلغاء");
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 100, 40));

        jButton6.setFont(new java.awt.Font("Cairo ExtraBold", 1, 18)); // NOI18N
        jButton6.setText("مصادقة");
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 310, 100, 40));

        jLabel89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icons8-immigration-64.png"))); // NOI18N
        jPanel6.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 70, -1));

        jPanel4.setBackground(new java.awt.Color(23, 36, 50));
        jPanel4.setPreferredSize(new java.awt.Dimension(450, 400));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel71.setFont(new java.awt.Font("Cairo SemiBold", 1, 18)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("إسم التلميذ");
        jPanel4.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 25, -1, -1));

        jLabel72.setFont(new java.awt.Font("Cairo SemiBold", 0, 16)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("السنة الدراسية");
        jPanel4.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 100, -1, -1));

        jLabel73.setFont(new java.awt.Font("Cairo SemiBold", 0, 16)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("القسم");
        jPanel4.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 170, -1, -1));

        jLabel74.setFont(new java.awt.Font("Cairo SemiBold", 0, 16)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("سبب الغياب");
        jPanel4.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 230, -1, -1));

        jTextField3.setText("jTextField3");
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 200, 45));

        jTextField4.setText("jTextField4");
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 200, 45));

        jTextField5.setText("jTextField5");
        jPanel4.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 200, 45));

        jButton3.setFont(new java.awt.Font("Cairo ExtraBold", 1, 18)); // NOI18N
        jButton3.setText("إلغاء");
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 100, 40));

        jButton4.setFont(new java.awt.Font("Cairo ExtraBold", 1, 18)); // NOI18N
        jButton4.setText("مصادقة");
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 310, 100, 40));

        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icons8-immigration-64.png"))); // NOI18N
        jPanel4.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignatureVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignatureVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignatureVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignatureVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignatureVue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
